package com.matas.enums;


public enum MisfirePocliy {
	MISFIRE_INSTRUCTION_FIRE_NOW, //
	MISFIRE_INSTRUCTION_IGNORE_MISFIRE_POLICY, //
	MISFIRE_INSTRUCTION_RESCHEDULE_NEXT_WITH_EXISTING_COUNT, //
	MISFIRE_INSTRUCTION_RESCHEDULE_NEXT_WITH_REMAINING_COUNT, //
	MISFIRE_INSTRUCTION_RESCHEDULE_NOW_WITH_EXISTING_REPEAT_COUNT, //
	MISFIRE_INSTRUCTION_RESCHEDULE_NOW_WITH_REMAINING_REPEAT_COUNT, //
	MISFIRE_INSTRUCTION_DO_NOTHING, //
	MISFIRE_INSTRUCTION_FIRE_ONCE_NOW, //
	;
}
